### ISSUE TITLE
Cant play with Xaero's Mini-map

### ISSUE THREAD

**Issue by Pogkin** [fzzyhmstrs/ac#2]
I cant play with Xaeros Mini-map, it just says this
![image](https://user-images.githubusercontent.com/110632220/182936805-9caf242a-cf15-40fe-8c96-d2b7cb9f9dde.png)

**Comment by Pogkin** [comment]
![image](https://user-images.githubusercontent.com/110632220/182936893-4b4c8e17-35ea-4f75-a40b-6fa37163ca05.png)

**Comment by fzzyhmstrs** [comment]
What versions of my mods are you playing with? Because the identifier for that entity should be "amethyst_core:missile_entity"

**Comment by fzzyhmstrs** [comment]
With the below version combinations I am not able to replicate the above issue.

Amethyst Imbuement 1.18.2-24 / Amethyst Core 0.2.3+1.18.2 / Xaero's Minimap 22.12.0 for 1.18.2

Amethyst Imbuement 1.9-05 or -07 / Amethyst Core 0.2.0+1.19 or 0.2.3+1.19 / Xaero's Minimap 22.12.0 for 1.19
